package automation;

import java.util.Set;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.Alert;

import org.openqa.selenium.By;
 
import org.openqa.selenium.WebDriver;
 
import org.openqa.selenium.firefox.FirefoxDriver;

 
public class SeventhTestCase {
 
    private static WebDriver driver = null;
 
    public static void main(String[] args) {
 
        // Create a new instance of the Firefox driver
 
        driver = new FirefoxDriver();
 
        //Put a Implicit wait, this means that any search for elements on the page could take the time the implicit wait is set for before throwing exception
 
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
 
        //Launch the Online Store Website
        //2) Open URL “http://www.toolsqa.com/automation-practice-switch-windows/” 
        driver.get("http://www.toolsqa.com/automation-practice-switch-windows/");
        
        //3) Click on Button “Alert Box”, it will open a Pop Up Window generated by JavaScript
        //driver.findElement(By.id("alert")).click();
        //driver.findElement(By.xpath("//button[@onclick='newAlert()']")).click();
        //driver.findElement(By.xpath("//button[@onclick='newMsgWin()']")).click();

        System.out.println(driver.findElements(By.xpath("//button[@onclick='newAlert()']")).toString());
        
        //4) Switch to Alert window (Use ‘SwitchTo()Alert() command)
        Alert myAlert = driver.switchTo().alert();
        myAlert.accept();
        
        //5) Close the Pop Up Window (Use Accept command)
        driver.close();
    }
}